[package]
name = "crypter"
version = "0.1.0"
authors = ["doctor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
short-crypt = "1.0.14"