[package]
name = "myenum"
version = "0.1.0"
authors = ["faisalrwp <faisal.rwp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
